# T:17 - Pandas Introduction 
1. Task 2nd
2. Data analysis using pandas
3. Data Structures: Series (1D) and DataFrame (2D)
4. Reading & Writing: Supports CSV, Excel, JSON, SQL, etc.
5. Data Cleaning: Handling missing data, duplicates, filtering
6. Data Transformation: Sorting, merging, reshaping
7. Statistical Analysis: Aggregation, group operations
8. Integration: Works well with NumPy, Matplotlib, and Scikit-learn

In [2]:
# Project 2

In [4]:
import pandas as pd

In [6]:
pd.__version__

'2.2.2'

In [8]:
df = pd.read_csv(r"I:\My Drive\Nareshit DS\Regular Notes\0-feb\13-feb\data.csv")

In [10]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [12]:
len(df)

195

In [14]:
df.shape

(195, 5)

In [16]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [18]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [22]:
len(df.columns)

5

In [24]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [26]:
df.head(12)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income
10,Azerbaijan,AZE,18.300,58.7000,Upper middle income
11,Burundi,BDI,44.151,1.3000,Low income

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [32]:
df.tail(3)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [34]:
df[:2]

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [36]:
df[:5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [38]:
df[0:190:25]

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244      78.900000          High income
25     Barbados         BRB     12.188      73.000000          High income
50      Ecuador         ECU     21.070      40.353684  Upper middle income
75     Honduras         HND     21.593      17.800000  Lower middle income
100       Libya         LBY     21.425      16.500000  Upper middle income
125     Namibia         NAM     29.937      13.900000  Upper middle income
150       Sudan         SDN     33.477      22.700000  Lower middle income
175     Tunisia         TUN     19.800      43.800000  Upper middle income

In [40]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

Generate descriptive statistics.

Descriptive statistics include those that summarize the central
tendency, dispersion and shape of a
dataset's distribution, excluding ``NaN`` values.

In [43]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

In [45]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [47]:
df.columns = ['a','b', 'c' , 'd', 'e']

In [49]:
df

                        a    b       c     d                    e
0                   Aruba  ABW  10.244  78.9          High income
1             Afghanistan  AFG  35.253   5.9           Low income
2                  Angola  AGO  45.985  19.1  Upper middle income
3                 Albania  ALB  12.877  57.2  Upper middle income
4    United Arab Emirates  ARE  11.044  88.0          High income
..                    ...  ...     ...   ...                  ...
190           Yemen, Rep.  YEM  32.947  20.0  Lower middle income
191          South Africa  ZAF  20.850  46.5  Upper middle income
192      Congo, Dem. Rep.  COD  42.394   2.2           Low income
193                Zambia  ZMB  40.471  15.4  Lower middle income
194              Zimbabwe  ZWE  35.715  18.5           Low income

[195 rows x 5 columns]

In [51]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [55]:
df.columns = ['a','b', 'c' , 'd', 'e','w']

ValueError: Length mismatch: Expected axis has 5 elements, new values have 6 elements

In [57]:
df.head(1)

       a    b       c     d            e
0  Aruba  ABW  10.244  78.9  High income

In [59]:
df.columns = ['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup']

In [61]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [63]:
df[['CountryName', 'CountryCode']]

              CountryName CountryCode
0                   Aruba         ABW
1             Afghanistan         AFG
2                  Angola         AGO
3                 Albania         ALB
4    United Arab Emirates         ARE
..                    ...         ...
190           Yemen, Rep.         YEM
191          South Africa         ZAF
192      Congo, Dem. Rep.         COD
193                Zambia         ZMB
194              Zimbabwe         ZWE

[195 rows x 2 columns]

In [65]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [67]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [69]:
df.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [71]:
df_categorical =df [['CountryName', 'CountryCode','IncomeGroup']]

In [73]:
df_categorical.head(10)

            CountryName CountryCode          IncomeGroup
0                 Aruba         ABW          High income
1           Afghanistan         AFG           Low income
2                Angola         AGO  Upper middle income
3               Albania         ALB  Upper middle income
4  United Arab Emirates         ARE          High income
5             Argentina         ARG          High income
6               Armenia         ARM  Lower middle income
7   Antigua and Barbuda         ATG          High income
8             Australia         AUS          High income
9               Austria         AUT          High income

In [75]:
df_numerical = df [['BirthRate', 'InternetUsers']]

In [77]:
df_numerical

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [79]:
df_categorical.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [81]:
df_numerical.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [83]:
ct_data = df.select_dtypes(include=['object']).columns

In [85]:
ct_data

Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [91]:
# *******************************

# 🔹 1. Efficient Data Loading & Memory Optimization

In [102]:
df = pd.read_csv(r"I:\My Drive\Nareshit DS\Regular Notes\0-feb\13-feb\data.csv",low_memory=False, dtype={'CountryCode': 'category'})

In [104]:
df.memory_usage(deep=True).sum() / (1024**2)  # Convert bytes to MB

0.03982067108154297

# 🔹 2. Better Missing Data Handling

In [109]:
df.isna().mean() *100 #Signature: df.isna() -> 'DataFrame'Docstring:Detect missing values.
# shows % of value per column

CountryName      0.0
CountryCode      0.0
BirthRate        0.0
InternetUsers    0.0
IncomeGroup      0.0
dtype: float64

In [111]:
df.dropna(axis=0, thresh=3) # drops rows with less than 3 valid valuse

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

1. .dropna()  # Removes rows or columns with missing (NaN) values
2. axis = 0 # Drops rowas
3. axis = 1 #(use axis=1 to drop column)
4. thresh = 3 # keeps rows that have at least 3 non-NaN values .
   - ** if a row has less than 3 valid values , it will be remove

In [114]:
df.fillna(df.median(numeric_only=True), inplace=True) # fills with median Value

# 🔹 3. Using .query() for Faster Filtering

In [117]:
df[df['BirthRate']> 30]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90,Low income
2,Angola,AGO,45.985,19.10,Upper middle income
11,Burundi,BDI,44.151,1.30,Low income
13,Benin,BEN,36.440,4.90,Low income
14,Burkina Faso,BFA,40.551,9.10,Low income
29,Central African Republic,CAF,34.076,3.50,Low income
34,Cote d'Ivoire,CIV,37.320,8.40,Lower middle income
35,Cameroon,CMR,37.236,6.40,Lower middle income
36,"Congo, Rep.",COG,37.011,6.60,Lower middle income
38,Comoros,COM,34.326,6.50,Low income
52,Eritrea,ERI,34.800,0.90,Low income
55,Ethiopia,ETH,32.925,1.90,Low income
60,Gabon,GAB,30.555,9.20,Upper middle income
63,Ghana,GHA,33.131,12.30,Lower middle income
64,Guinea,GIN,37.337,1.60,Low income
65,"Gambia, The",GMB,42.525,14.00,Low income
66,Guinea-Bissau,GNB,37.503,3.10,Low income
67,Equatorial Guinea,GNQ,35.362,16.40,High income
83,Iraq,IRQ,31.093,9.20,Upper middle income
91,Kenya,KEN,35.194,39.00,Lower middle income
99,Liberia,LBR,35.521,3.20,Low income
111,Madagascar,MDG,34.686,3.00,Low income
115,Mali,MLI,44.138,3.50,Low income
120,Mozambique,MOZ,39.705,5.40,Low income
121,Mauritania,MRT,33.801,6.20,Lower middle income
123,Malawi,MWI,39.459,5.05,Low income
127,Niger,NER,49.661,1.70,Low income
128,Nigeria,NGA,40.045,38.00,Lower middle income
148,Rwanda,RWA,32.689,9.00,Low income
150,Sudan,SDN,33.477,22.70,Lower middle income
151,Senegal,SEN,38.533,13.10,Lower middle income
153,Solomon Islands,SLB,30.578,8.00,Lower middle income
154,Sierra Leone,SLE,36.729,1.70,Low income
156,Somalia,SOM,43.891,1.50,Low income
158,South Sudan,SSD,37.126,14.10,Low income
159,Sao Tome and Principe,STP,34.537,23.00,Lower middle income
164,Swaziland,SWZ,30.093,24.70,Lower middle income
167,Chad,TCD,45.745,2.30,Low income
168,Togo,TGO,36.080,4.50,Low income
170,Tajikistan,TJK,30.792,16.00,Lower middle income
172,Timor-Leste,TLS,35.755,1.10,Lower middle income
177,Tanzania,TZA,39.518,4.40,Low income
178,Uganda,UGA,43.474,16.20,Low income
188,West Bank and Gaza,PSE,30.394,46.60,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.00,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income
193,Zambia,ZMB,40.471,15.40,Lower middle income
194,Zimbabwe,ZWE,35.715,18.50,Low income

1. df['BirthRate'] > 30 creates a boolean mask (True/False values).
2. "BirthRate > 30" is evaluated as a string.
3. Pandas processes it internally using a faster engine, improving performance.

In [119]:
df.query("BirthRate > 30")

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90,Low income
2,Angola,AGO,45.985,19.10,Upper middle income
11,Burundi,BDI,44.151,1.30,Low income
13,Benin,BEN,36.440,4.90,Low income
14,Burkina Faso,BFA,40.551,9.10,Low income
29,Central African Republic,CAF,34.076,3.50,Low income
34,Cote d'Ivoire,CIV,37.320,8.40,Lower middle income
35,Cameroon,CMR,37.236,6.40,Lower middle income
36,"Congo, Rep.",COG,37.011,6.60,Lower middle income
38,Comoros,COM,34.326,6.50,Low income
52,Eritrea,ERI,34.800,0.90,Low income
55,Ethiopia,ETH,32.925,1.90,Low income
60,Gabon,GAB,30.555,9.20,Upper middle income
63,Ghana,GHA,33.131,12.30,Lower middle income
64,Guinea,GIN,37.337,1.60,Low income
65,"Gambia, The",GMB,42.525,14.00,Low income
66,Guinea-Bissau,GNB,37.503,3.10,Low income
67,Equatorial Guinea,GNQ,35.362,16.40,High income
83,Iraq,IRQ,31.093,9.20,Upper middle income
91,Kenya,KEN,35.194,39.00,Lower middle income
99,Liberia,LBR,35.521,3.20,Low income
111,Madagascar,MDG,34.686,3.00,Low income
115,Mali,MLI,44.138,3.50,Low income
120,Mozambique,MOZ,39.705,5.40,Low income
121,Mauritania,MRT,33.801,6.20,Lower middle income
123,Malawi,MWI,39.459,5.05,Low income
127,Niger,NER,49.661,1.70,Low income
128,Nigeria,NGA,40.045,38.00,Lower middle income
148,Rwanda,RWA,32.689,9.00,Low income
150,Sudan,SDN,33.477,22.70,Lower middle income
151,Senegal,SEN,38.533,13.10,Lower middle income
153,Solomon Islands,SLB,30.578,8.00,Lower middle income
154,Sierra Leone,SLE,36.729,1.70,Low income
156,Somalia,SOM,43.891,1.50,Low income
158,South Sudan,SSD,37.126,14.10,Low income
159,Sao Tome and Principe,STP,34.537,23.00,Lower middle income
164,Swaziland,SWZ,30.093,24.70,Lower middle income
167,Chad,TCD,45.745,2.30,Low income
168,Togo,TGO,36.080,4.50,Low income
170,Tajikistan,TJK,30.792,16.00,Lower middle income
172,Timor-Leste,TLS,35.755,1.10,Lower middle income
177,Tanzania,TZA,39.518,4.40,Low income
178,Uganda,UGA,43.474,16.20,Low income
188,West Bank and Gaza,PSE,30.394,46.60,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.00,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income
193,Zambia,ZMB,40.471,15.40,Lower middle income
194,Zimbabwe,ZWE,35.715,18.50,Low income

# 🔹 5. .value_counts() with Normalization

In [123]:
df['IncomeGroup'].value_counts(normalize=True) * 100  # Shows % distribution

IncomeGroup
High income            34.358974
Lower middle income    25.641026
Upper middle income    24.615385
Low income             15.384615
Name: proportion, dtype: float64