In [1]:
import pandas as pd
import numpy as np

In [2]:
rd = pd.read_excel(r"I:\My Drive\Nareshit DS\Regular Notes\0-feb\17-feb\Book3.xlsx")

In [3]:
rd

,ADDRES,date,time
0,"56th ben colony, btm layout, bangalore 78909",3rd apr 2022,5hr 55 min 8sec
1,"20th stree, johns road, whitefield, bangalore ...",2021-12-06 00:00:00,0.280741

In [4]:
id(rd)

2485044356880

In [5]:
rd.columns

Index(['ADDRES', 'date', 'time'], dtype='object')

In [6]:
rd.describe()

,ADDRES,date,time
count,2,2,2
unique,2,2,2
top,"56th ben colony, btm layout, bangalore 78909",3rd apr 2022,5hr 55 min 8sec
freq,1,1,1

In [8]:
rd.shape

(2, 3)

In [9]:
rd.ADDRES

0        56th ben colony, btm layout, bangalore 78909
1    20th stree, johns road, whitefield, bangalore ...
Name: ADDRES, dtype: object

In [10]:
rd.date

0           3rd apr 2022
1    2021-12-06 00:00:00
Name: date, dtype: object

In [11]:
rd.time

0    5hr 55 min 8sec
1           0.280741
Name: time, dtype: object

In [12]:
cln_data = rd['ADDRES'].str.split(r',',expand=True)
cln_data

                 0            1                  2                 3
0  56th ben colony   btm layout   bangalore 78909               None
1       20th stree   johns road         whitefield   bangalore - 567

In [14]:
cln_data.columns = ['Street_name', 'Area', 'City', 'PIN']
cln_data

       Street_name         Area               City               PIN
0  56th ben colony   btm layout   bangalore 78909               None
1       20th stree   johns road         whitefield   bangalore - 567

In [17]:
print(rd.columns.tolist())

['ADDRES', 'date', 'time']

In [18]:
new_data= rd['ADDRES'].str.split(r'[,-]', expand=True)
new_data

                 0            1                  2            3     4
0  56th ben colony   btm layout   bangalore 78909          None  None
1       20th stree   johns road         whitefield   bangalore    567

In [19]:
new_data.columns = ["ADDRES", "colony " , "area" , "City","PIN"]

In [20]:
new_data

            ADDRES      colony                area         City   PIN
0  56th ben colony   btm layout   bangalore 78909          None  None
1       20th stree   johns road         whitefield   bangalore    567

In [21]:
rd.date

0           3rd apr 2022
1    2021-12-06 00:00:00
Name: date, dtype: object

In [22]:
rd.time

0    5hr 55 min 8sec
1           0.280741
Name: time, dtype: object

### Selecting the 'date' Column
```python
rd['date']
```
This selects the **'date'** column from the DataFrame `rd`, which contains date strings.

### Applying Regular Expression (Regex)
```python
.str.extract(r'(\d+)(st|nd|rd|th)?\s(\w+)\s+(\d+)', expand=True)
```
This applies a **regular expression (regex)** to extract parts of the date string.

### Regex Pattern Breakdown
- `(\d+)` → Captures **one or more digits** (day part).
- `(st|nd|rd|th)?` → Optionally captures **ordinal suffixes** like **"st", "nd", "rd", or "th"**.
- `\s` → Matches a **space**.
- `(\w+)` → Captures the **month name** (a sequence of word characters).
- `\s+` → Matches **one or more spaces**.
- `(\d+)` → Captures **one or more digits** (year part).

### `expand=True`
Ensures that the extracted components are returned as a **new DataFrame** with multiple columns.

In [24]:
cln_date = rd['date'].str.extract(r'(\d+)(st|nd|rd|th)?\s(\w+)\s+(\d+)', expand=True)
cln_date

     0    1    2     3
0    3   rd  apr  2022
1  NaN  NaN  NaN   NaN

In [25]:
cln_date = cln_date.iloc[:,[0,2,3]]
cln_date

     0    2     3
0    3  apr  2022
1  NaN  NaN   NaN

In [26]:
cln_date.columns = ["Date", "Month", "Year"]
cln_date

  Date Month  Year
0    3   apr  2022
1  NaN   NaN   NaN

In [27]:
rd["time"] = rd["time"].astype(str)
cln_time = rd["time"].str.split(r'[:\s]+',expand = True)
cln_time

                     0     1     2     3
0                  5hr    55   min  8sec
1  0.28074074074074074  None  None  None

In [28]:
cln_time.columns = ["Hrs","Mins","sec",""]
cln_time

                   Hrs  Mins   sec
0                  5hr    55   min  8sec
1  0.28074074074074074  None  None  None

# Some Improvement

In [45]:
df = pd.read_excel(r"I:\My Drive\Nareshit DS\Regular Notes\0-feb\17-feb\Book3.xlsx")

In [46]:
df.columns

Index(['ADDRES', 'date', 'time'], dtype='object')

In [47]:
split_add = df['ADDRES'].str.split(r'[,-]\s*', expand=True)
split_add

                 0           1                 2           3     4
0  56th ben colony  btm layout  bangalore 78909         None  None
1       20th stree  johns road        whitefield  bangalore    567

In [48]:
split_add.columns = ['Street','colony', 'Area', 'City', 'PIN']
split_add

            Street      colony              Area        City   PIN
0  56th ben colony  btm layout  bangalore 78909         None  None
1       20th stree  johns road        whitefield  bangalore    567

In [53]:
split_date = df['date'].str.extract(r'(\d+)(st|nd|rd|th)?\s(\w+)\s+(\d+)', expand=True)
split_date

     0    1    2     3
0    3   rd  apr  2022
1  NaN  NaN  NaN   NaN

In [55]:
split_date=  split_date.iloc[:,[0,2,3]]
split_date

     0    2     3
0    3  apr  2022
1  NaN  NaN   NaN

In [56]:
split_date.columns = ["Date", "Month", "Year"]
split_date

  Date Month  Year
0    3   apr  2022
1  NaN   NaN   NaN

In [57]:
df["time"] = df["time"].astype(str)
split_time = df["time"].str.split(r'[:\s]+',expand = True)
split_time.columns = ["Hrs","Mins","sec",""]
split_time

                   Hrs  Mins   sec
0                  5hr    55   min  8sec
1  0.28074074074074074  None  None  None

In [59]:
# Combine all cleaned attributes into clean_data
clean_data = pd.concat([df, split_add, split_date, split_time], axis=1)

# Drop the original columns if needed
clean_data = clean_data.drop(columns=['ADDRES', 'date', 'time'])

# Display the cleaned data
clean_data.head()

,Street,colony,Area,City,PIN,Date,Month,Year,Hrs,Mins,sec,
0,56th ben colony,btm layout,bangalore 78909,None,None,3,apr,2022,5hr,55,min,8sec
1,20th stree,johns road,whitefield,bangalore,567,NaN,NaN,NaN,0.28074074074074074,None,None,None